'use strict';

/**
 * src/modules/employer/models/employer.model.js
 *
 * Employer Integration data model helpers
 * ---------------------------------------
 * Supabase-first row builders and table metadata.
 *
 * Tables:
 * - emp_employers
 * - emp_employer_users
 * - emp_job_roles
 * - emp_talent_signals
 *
 * Notes:
 * - IDs should be UUIDs generated by PostgreSQL
 * - created_at / updated_at handled by DB defaults + triggers
 * - nested objects assume JSONB columns
 * - all builders return insert-safe row payloads
 */

const TABLES = Object.freeze({
  EMPLOYERS: 'emp_employers',
  EMPLOYER_USERS: 'emp_employer_users',
  JOB_ROLES: 'emp_job_roles',
  TALENT_SIGNALS: 'emp_talent_signals',
});

const EMPLOYER_ROLES = Object.freeze({
  ADMIN: 'employer_admin',
  HR: 'employer_hr',
});

/**
 * Build employer insert row
 */
function buildEmployerRow(createdBy, fields = {}) {
  return {
    company_name: String(fields.company_name || '').trim(),
    industry: fields.industry?.trim?.() || null,
    website: fields.website?.trim?.() || null,
    created_by: createdBy,
  };
}

/**
 * Build employer membership insert row
 */
function buildEmployerUserRow(employerId, userId, role) {
  return {
    employer_id: employerId,
    user_id: userId,
    role,
  };
}

/**
 * Build job role insert/update row
 *
 * JSONB columns expected:
 * - salary_range
 * - experience_years
 */
function buildJobRoleRow(employerId, fields = {}) {
  const salaryMin = Number(fields.salary_min);
  const salaryMax = Number(fields.salary_max);
  const expMin = Number(fields.exp_min);
  const expMax = Number(fields.exp_max);

  return {
    employer_id: employerId,
    role_name: String(fields.role_name || '').trim(),
    required_skills: Array.isArray(fields.required_skills)
      ? fields.required_skills.filter(Boolean)
      : [],
    salary_range: {
      min: Number.isFinite(salaryMin) ? salaryMin : 0,
      max: Number.isFinite(salaryMax) ? salaryMax : 0,
      currency: fields.currency?.trim?.() || 'USD',
    },
    streams: Array.isArray(fields.streams)
      ? fields.streams.filter(Boolean)
      : [],
    experience_years: {
      min: Number.isFinite(expMin) ? expMin : 0,
      max: Number.isFinite(expMax) ? expMax : 5,
    },
    active: true,
  };
}

module.exports = {
  TABLES,
  EMPLOYER_ROLES,
  buildEmployerRow,
  buildEmployerUserRow,
  buildJobRoleRow,
};