'use strict';

/**
 * routes/student-onboarding.routes.js
 * Mounted at: /api/v1/student-onboarding
 *
 * PATCH: ETag correctness — POST /complete now explicitly bumps users.updated_at
 * after the RPC so the lightweight freshness token used by GET /me and
 * GET /app-entry is invalidated when student_onboarding_complete flips.
 *
 * Root cause:
 *   complete_student_onboarding RPC sets student_onboarding_complete = true
 *   in the users table, but there is no guarantee the RPC bumps users.updated_at.
 *   If it does not, the ETag generated by fetchUserFreshnessMetadata() would
 *   remain unchanged and GET /me / GET /app-entry would incorrectly return 304.
 *
 * Fix strategy:
 *   After the RPC succeeds, issue an explicit UPDATE users SET updated_at = now
 *   WHERE id = userId. This is idempotent and safe: even if the RPC already
 *   bumped updated_at, a second identical timestamp write is a no-op on the
 *   ETag (same value → same hash). The only cost is one extra cheap UPDATE on
 *   the 304-invalidation hot path, which runs at most once per student
 *   lifecycle.
 *
 * Phase 1 MVP additions:
 *   POST /generate-recommendations  — triggers Claude AI recommendation engine
 *   GET  /results                   — authoritative status/result contract;
 *                                      returns not_started | pending | ready
 *                                      | failed (Phase 1 Pass 5 — see the
 *                                      GET /results handler below for the
 *                                      full contract).
 *
 * NOTE: recommendation-engine is loaded lazily (inside the handler, not at
 * module load time). This means the server boots safely even if the file has
 * not been deployed yet — the route returns 503 instead of crashing the process.
 * Once the file is in place at:
 *   src/modules/student-onboarding/services/recommendation-engine.js
 * the require will resolve on the first request with no restart needed.
 */

const { Router } = require('express');
const { body } = require('express-validator');

const { validate } = require('../middleware/requestValidator');
const { asyncHandler } = require('../utils/helpers');
const { AppError, ErrorCodes } = require('../middleware/errorHandler');
const supabase = require('../lib/supabaseClient');
const logger = require('../utils/logger');
const freshnessCache = require('../utils/freshnessCache');

const router = Router();

const MAX_ARRAY_10 = 10;
const MAX_ARRAY_20 = 20;
const MAX_ARRAY_5 = 5;

function getUserId(req) {
  const userId =
    req.user?.id ||
    req.auth?.userId ||
    req.user?.user_id ||
    req.user?.uid;

  if (!userId || typeof userId !== 'string') {
    throw new AppError('Unauthorized', 401, {}, ErrorCodes.UNAUTHORIZED);
  }

  return userId;
}

function buildStudentProfile(payload) {
  return {
    age: payload.age,
    grade: payload.grade,
    country: payload.country,
    preferred_subjects: payload.preferred_subjects || [],
    interests: payload.interests || [],
    strengths: payload.strengths || {},
    career_curiosities: payload.career_curiosities || [],
    learning_styles: payload.learning_styles || [],
    academic_marks: payload.academic_marks || null,
  };
}

// PATCH /draft
router.patch(
  '/draft',
  validate([
    body('age').optional({ nullable: true }).isInt({ min: 10, max: 30 }),
    body('grade').optional().isString().trim().isLength({ max: 100 }),
    body('country').optional().isString().trim().isLength({ max: 100 }),
    body('preferred_subjects').optional().isArray({ max: MAX_ARRAY_20 }),
    body('interests').optional().isArray({ max: MAX_ARRAY_10 }),
    body('strengths').optional().isObject(),
    body('career_curiosities').optional().isArray({ max: MAX_ARRAY_10 }),
    body('learning_styles').optional().isArray({ max: MAX_ARRAY_5 }),
    body('academic_marks').optional().isObject(),
  ]),
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { error } = await supabase
      .from('student_onboarding_drafts')
      .upsert(
        { user_id: userId, ...req.body },
        { onConflict: 'user_id' },
      );

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    return res.status(200).json({ success: true, data: { saved: true } });
  }),
);

// GET /draft
router.get(
  '/draft',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { data, error } = await supabase
      .from('student_onboarding_drafts')
      .select(
        'age,grade,country,preferred_subjects,interests,strengths,career_curiosities,learning_styles,academic_marks',
      )
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    return res.status(200).json({ success: true, data: { draft: data || null } });
  }),
);

// POST /complete
router.post(
  '/complete',
  validate([
    body('age').isInt({ min: 10, max: 30 }),
    body('grade').isString().trim().notEmpty(),
    body('country').isString().trim().notEmpty(),
    body('preferred_subjects').optional().isArray(),
    body('interests').isArray({ min: 1 }),
    body('strengths').isObject(),
    body('strengths.problem_solving').isInt({ min: 1, max: 5 }),
    body('strengths.creativity').isInt({ min: 1, max: 5 }),
    body('strengths.communication').isInt({ min: 1, max: 5 }),
    body('strengths.mathematics').isInt({ min: 1, max: 5 }),
    body('strengths.leadership').isInt({ min: 1, max: 5 }),
    body('career_curiosities').isArray({ min: 1 }),
    body('learning_styles').isArray({ min: 1 }),
    body('academic_marks').optional().isObject(),
  ]),
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);
    const studentProfile = buildStudentProfile(req.body);

    const { error } = await supabase.rpc(
      'complete_student_onboarding',
      { p_user_id: userId, p_profile: studentProfile },
    );

    if (error) {
      throw new AppError(
        error.message, 500, { code: error.code, hint: error.hint }, ErrorCodes.INTERNAL_ERROR,
      );
    }

    // ── ETag INVALIDATION FIX ────────────────────────────────────────────────
    // The complete_student_onboarding RPC sets student_onboarding_complete = true
    // in the users table but may not bump users.updated_at.
    // Without this UPDATE, the lightweight freshness token built by
    // fetchUserFreshnessMetadata() in GET /me would remain stale, causing the
    // next GET /me to incorrectly return 304 with the old onboarding state.
    //
    // We explicitly bump updated_at here so the ETag changes.
    // Non-fatal: a failure here only affects caching correctness for this request;
    // it does not corrupt user data.
    const { error: touchErr } = await supabase
      .from('users')
      .update({ updated_at: new Date().toISOString() })
      .eq('id', userId);

    if (touchErr) {
      logger.warn('[StudentOnboarding] updated_at bump failed — ETag may be stale', {
        userId,
        err: touchErr.message,
      });
    }
    // ── END ETag INVALIDATION FIX ────────────────────────────────────────────

    // Phase 2: invalidate freshness cache — student_onboarding_complete has changed.
    freshnessCache.del(`app-entry:${userId}`);
    freshnessCache.del(`user-me:${userId}`);

    logger.info(
      '[StudentOnboarding] Profile created and onboarding completed',
      { userId, interests: studentProfile.interests.length, curiosities: studentProfile.career_curiosities.length },
    );

    return res.status(200).json({
      success: true,
      data: { message: 'Student career profile created. Onboarding complete.' },
    });
  }),
);

// GET /profile
router.get(
  '/profile',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { data, error } = await supabase
      .from('student_career_profiles')
      .select(
        'age,grade,country,preferred_subjects,interests,strengths,career_curiosities,learning_styles,academic_marks,profile_version',
      )
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    return res.status(200).json({ success: true, data: { profile: data || null } });
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// PHASE 1 MVP — AI RECOMMENDATION ROUTES
// ─────────────────────────────────────────────────────────────────────────────

// POST /generate-recommendations
// LEGACY / ORPHANED — Phase 1 Pass 4 audit confirmed no current frontend
// code calls this route (only a stray comment in front/src/routes/index.tsx
// references the path) and no other backend caller exists. It remains
// mounted with `authenticate` (server.js) and is kept reachable rather than
// deleted, per spec, in case an untraced external caller depends on it.
//
// AUDIT FINDING — uncontrolled alternate generation path:
// This handler previously called engine.generateRecommendations(userId)
// DIRECTLY. generateRecommendations() has no internal precondition check —
// it calls the Claude provider unconditionally every time it is invoked.
// Calling this route bypassed:
//   - the atomic duplicate-guard in initiateGeneration() (the conditional
//     upsert with ignoreDuplicates that makes the backend-owned
//     aspiration -> processing trigger safe against duplicate/racing
//     generation — see recommendation-lifecycle.service.js);
//   - CreditGuard, AI rate limiting, and tier quota (none of which this
//     route ever had wired);
// meaning repeated requests to this authenticated-but-unwired route could
// fire multiple concurrent/racing AI provider calls for the same user with
// no dedup and no abuse protection, independent of the (already free)
// studentRecommendation credit cost.
//
// CONTAINMENT (smallest safe fix — spec §12 "preferred if safe"):
// The route now delegates to the SAME guarded lifecycle entry point,
// initiateGeneration(userId), instead of calling generateRecommendations()
// directly. initiateGeneration()'s conditional upsert ensures only the
// first caller to observe a missing/'not_started' row ever launches
// generation; every subsequent call (from this route, or from the
// aspiration-triggered backend flow, in any order) is a safe no-op. This
// makes duplicate/racing generation from repeated calls to this legacy
// route structurally impossible, without adding a second, competing
// generation implementation and without wiring CreditGuard/rate-limit/
// quota here (those protect the repeatable retry/regeneration path — see
// recommendation.routes.js — not this now-idempotent initial-trigger path,
// which cannot be abused into repeated AI spend once dedup-guarded).
//
// `userId` is taken exclusively from the authenticated request (getUserId,
// same as every other handler in this file) — never from req.body. There
// is a separate, unused handleGenerateRecommendations() export in
// recommendation-engine.js that reads `userId` from req.body; it is dead
// code (not required/wired by any route in this repository) and is
// intentionally NOT used here, since wiring it as-is would let one
// authenticated Student trigger generation for another Student's account.
// See the implementation report's "Remaining Risks" section.
//
// Returns 202 immediately — generation runs async. The frontend polls
// GET /results every 3 s while on the ProcessingStep screen. Response
// contract is unchanged from before this pass.
//
// The engine module is required lazily inside the handler so that a missing
// file never crashes the server at boot (returns 503 instead).
router.post(
  '/generate-recommendations',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    // Lazy require — safe even if the file is not yet deployed
    let engine;
    try {
      engine = require('../modules/student-onboarding/services/recommendation-engine');
    } catch (loadErr) {
      logger.error('[StudentOnboarding] recommendation-engine module not found', {
        userId,
        err: loadErr.message,
        hint: 'Deploy src/modules/student-onboarding/services/recommendation-engine.js',
      });
      throw new AppError(
        'Recommendation engine not available. Please deploy the Phase 1 service file.',
        503,
        { code: 'ENGINE_NOT_DEPLOYED' },
        ErrorCodes.INTERNAL_ERROR,
      );
    }

    logger.info('[StudentOnboarding] generate-recommendations requested', { userId });

    // Routed through the same guarded initiateGeneration() the
    // backend-owned aspiration->processing trigger uses — see the audit
    // finding above. Errors here are the atomic guard's own DB-level
    // failures only (generateRecommendations()'s own success/failure is
    // handled and persisted internally, fire-and-forget); swallow and log,
    // never fail this request on a best-effort generation kickoff.
    try {
      await engine.initiateGeneration(userId);
    } catch (err) {
      logger.error('[StudentOnboarding] generate-recommendations failed to initiate', {
        userId,
        err: err.message,
      });
    }

    return res.status(202).json({
      success: true,
      data: { message: 'Recommendation generation started. Poll GET /results for completion.' },
    });
  }),
);

// GET /results
//
// RESULTS / STATUS CONTRACT — Phase 1 Pass 5 (Results/status contract +
// frontend consumption).
//
// AUDIT FINDING (this pass): prior to this change, this endpoint only ever
// returned `{ result: null }` (no row / still generating) or
// `{ result, generatedAt, engineVersion }` (row present). It never exposed
// the `status` column that recommendation-engine.js has been writing
// ('pending' | 'ready' | 'failed') since Phase 1 Pass 2, and never exposed
// `error_detail` in any form. This made it structurally impossible for a
// client to distinguish "no row yet" (not_started) from "row exists but
// still pending" — both looked identical (`{ result: null }`) — and gave
// no way to render a failure state or offer retry.
//
// This endpoint now returns the full authoritative lifecycle contract:
//
//   not_started → { status: 'not_started' }
//   pending     → { status: 'pending' }
//   ready       → { status: 'ready', result, generatedAt, engineVersion }
//   failed      → { status: 'failed', message: <safe, student-facing text> }
//
// SAFE FAILURE MESSAGING:
//   `error_detail` is populated exclusively by
//   recommendation-engine.js#safeErrorDetail(), which already guarantees no
//   stack traces, provider payloads/headers, prompts, or credentials ever
//   reach that column (see its own file-level contract). This endpoint
//   still never returns the raw column name or any other DB-internal
//   shape — it surfaces error_detail's value under the generic `message`
//   field, and falls back to a generic student-facing message if it is
//   ever unexpectedly empty. No SQL detail, error code, or stack trace is
//   ever included.
//
// OWNERSHIP: unchanged — userId is always getUserId(req) (authenticated
// JWT via `authenticate` at the server.js mount point), the query is
// always scoped `.eq('user_id', userId)`, and nothing is ever read from
// req.body/req.params/req.query for identity. A client cannot fetch
// another Student's Recommendation.
//
// BACKWARD COMPATIBILITY: no current frontend code calls this endpoint
// (confirmed by repository search — see implementation report); the
// previous `{ result: ... }`-only shape had no live consumer, so this is
// a clean contract redesign rather than a breaking change to an active
// client.
router.get(
  '/results',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { data, error } = await supabase
      .from('student_recommendation_results')
      .select('status, error_detail, result_json, generated_at, engine_version')
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    // No row at all — generation has never been initiated for this user.
    if (!data) {
      return res.status(200).json({ success: true, data: { status: 'not_started' } });
    }

    if (data.status === 'pending') {
      return res.status(200).json({ success: true, data: { status: 'pending' } });
    }

    if (data.status === 'failed') {
      const safeMessage = typeof data.error_detail === 'string' && data.error_detail.trim()
        ? data.error_detail
        : "We couldn't generate your recommendation right now. Please try again.";

      return res.status(200).json({
        success: true,
        data: { status: 'failed', message: safeMessage },
      });
    }

    // status === 'ready' — the only remaining valid terminal state.
    let parsed;
    try {
      parsed = typeof data.result_json === 'string'
        ? JSON.parse(data.result_json)
        : data.result_json;
    } catch {
      throw new AppError(
        'Failed to parse recommendation result',
        500,
        {},
        ErrorCodes.INTERNAL_ERROR,
      );
    }

    return res.status(200).json({
      success: true,
      data: {
        status: 'ready',
        result: parsed,
        generatedAt: data.generated_at,
        engineVersion: data.engine_version,
      },
    });
  }),
);

module.exports = router;