'use strict';

/**
 * routes/student-onboarding.routes.js
 * Mounted at: /api/v1/student-onboarding
 *
 * PATCH: ETag correctness — POST /complete now explicitly bumps users.updated_at
 * after the RPC so the lightweight freshness token used by GET /me and
 * GET /app-entry is invalidated when student_onboarding_complete flips.
 *
 * Root cause:
 *   complete_student_onboarding RPC sets student_onboarding_complete = true
 *   in the users table, but there is no guarantee the RPC bumps users.updated_at.
 *   If it does not, the ETag generated by fetchUserFreshnessMetadata() would
 *   remain unchanged and GET /me / GET /app-entry would incorrectly return 304.
 *
 * Fix strategy:
 *   After the RPC succeeds, issue an explicit UPDATE users SET updated_at = now
 *   WHERE id = userId. This is idempotent and safe: even if the RPC already
 *   bumped updated_at, a second identical timestamp write is a no-op on the
 *   ETag (same value → same hash). The only cost is one extra cheap UPDATE on
 *   the 304-invalidation hot path, which runs at most once per student
 *   lifecycle.
 *
 * Phase 1 MVP additions:
 *   POST /generate-recommendations  — triggers Claude AI recommendation engine
 *   GET  /results                   — polls for completed RecommendationResult
 *
 * NOTE: recommendation-engine is loaded lazily (inside the handler, not at
 * module load time). This means the server boots safely even if the file has
 * not been deployed yet — the route returns 503 instead of crashing the process.
 * Once the file is in place at:
 *   src/modules/student-onboarding/services/recommendation-engine.js
 * the require will resolve on the first request with no restart needed.
 */

const { Router } = require('express');
const { body } = require('express-validator');

const { validate } = require('../middleware/requestValidator');
const { asyncHandler } = require('../utils/helpers');
const { AppError, ErrorCodes } = require('../middleware/errorHandler');
const supabase = require('../lib/supabaseClient');
const logger = require('../utils/logger');
const freshnessCache = require('../utils/freshnessCache');

const router = Router();

const MAX_ARRAY_10 = 10;
const MAX_ARRAY_20 = 20;
const MAX_ARRAY_5 = 5;

function getUserId(req) {
  const userId =
    req.user?.id ||
    req.auth?.userId ||
    req.user?.user_id ||
    req.user?.uid;

  if (!userId || typeof userId !== 'string') {
    throw new AppError('Unauthorized', 401, {}, ErrorCodes.UNAUTHORIZED);
  }

  return userId;
}

function buildStudentProfile(payload) {
  return {
    age: payload.age,
    grade: payload.grade,
    country: payload.country,
    preferred_subjects: payload.preferred_subjects || [],
    interests: payload.interests || [],
    strengths: payload.strengths || {},
    career_curiosities: payload.career_curiosities || [],
    learning_styles: payload.learning_styles || [],
    academic_marks: payload.academic_marks || null,
  };
}

// PATCH /draft
router.patch(
  '/draft',
  validate([
    body('age').optional({ nullable: true }).isInt({ min: 10, max: 30 }),
    body('grade').optional().isString().trim().isLength({ max: 100 }),
    body('country').optional().isString().trim().isLength({ max: 100 }),
    body('preferred_subjects').optional().isArray({ max: MAX_ARRAY_20 }),
    body('interests').optional().isArray({ max: MAX_ARRAY_10 }),
    body('strengths').optional().isObject(),
    body('career_curiosities').optional().isArray({ max: MAX_ARRAY_10 }),
    body('learning_styles').optional().isArray({ max: MAX_ARRAY_5 }),
    body('academic_marks').optional().isObject(),
  ]),
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { error } = await supabase
      .from('student_onboarding_drafts')
      .upsert(
        { user_id: userId, ...req.body },
        { onConflict: 'user_id' },
      );

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    return res.status(200).json({ success: true, data: { saved: true } });
  }),
);

// GET /draft
router.get(
  '/draft',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { data, error } = await supabase
      .from('student_onboarding_drafts')
      .select(
        'age,grade,country,preferred_subjects,interests,strengths,career_curiosities,learning_styles,academic_marks',
      )
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    return res.status(200).json({ success: true, data: { draft: data || null } });
  }),
);

// POST /complete
router.post(
  '/complete',
  validate([
    body('age').isInt({ min: 10, max: 30 }),
    body('grade').isString().trim().notEmpty(),
    body('country').isString().trim().notEmpty(),
    body('preferred_subjects').optional().isArray(),
    body('interests').isArray({ min: 1 }),
    body('strengths').isObject(),
    body('strengths.problem_solving').isInt({ min: 1, max: 5 }),
    body('strengths.creativity').isInt({ min: 1, max: 5 }),
    body('strengths.communication').isInt({ min: 1, max: 5 }),
    body('strengths.mathematics').isInt({ min: 1, max: 5 }),
    body('strengths.leadership').isInt({ min: 1, max: 5 }),
    body('career_curiosities').isArray({ min: 1 }),
    body('learning_styles').isArray({ min: 1 }),
    body('academic_marks').optional().isObject(),
  ]),
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);
    const studentProfile = buildStudentProfile(req.body);

    const { error } = await supabase.rpc(
      'complete_student_onboarding',
      { p_user_id: userId, p_profile: studentProfile },
    );

    if (error) {
      throw new AppError(
        error.message, 500, { code: error.code, hint: error.hint }, ErrorCodes.INTERNAL_ERROR,
      );
    }

    // ── ETag INVALIDATION FIX ────────────────────────────────────────────────
    // The complete_student_onboarding RPC sets student_onboarding_complete = true
    // in the users table but may not bump users.updated_at.
    // Without this UPDATE, the lightweight freshness token built by
    // fetchUserFreshnessMetadata() in GET /me would remain stale, causing the
    // next GET /me to incorrectly return 304 with the old onboarding state.
    //
    // We explicitly bump updated_at here so the ETag changes.
    // Non-fatal: a failure here only affects caching correctness for this request;
    // it does not corrupt user data.
    const { error: touchErr } = await supabase
      .from('users')
      .update({ updated_at: new Date().toISOString() })
      .eq('id', userId);

    if (touchErr) {
      logger.warn('[StudentOnboarding] updated_at bump failed — ETag may be stale', {
        userId,
        err: touchErr.message,
      });
    }
    // ── END ETag INVALIDATION FIX ────────────────────────────────────────────

    // Phase 2: invalidate freshness cache — student_onboarding_complete has changed.
    freshnessCache.del(`app-entry:${userId}`);
    freshnessCache.del(`user-me:${userId}`);

    logger.info(
      '[StudentOnboarding] Profile created and onboarding completed',
      { userId, interests: studentProfile.interests.length, curiosities: studentProfile.career_curiosities.length },
    );

    return res.status(200).json({
      success: true,
      data: { message: 'Student career profile created. Onboarding complete.' },
    });
  }),
);

// GET /profile
router.get(
  '/profile',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { data, error } = await supabase
      .from('student_career_profiles')
      .select(
        'age,grade,country,preferred_subjects,interests,strengths,career_curiosities,learning_styles,academic_marks,profile_version',
      )
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    return res.status(200).json({ success: true, data: { profile: data || null } });
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// PHASE 1 MVP — AI RECOMMENDATION ROUTES
// ─────────────────────────────────────────────────────────────────────────────

// POST /generate-recommendations
// Triggered by the frontend after Step 6 (financial) completes.
// Calls Claude with the student's full 6-step profile and writes a structured
// RecommendationResult to student_recommendation_results.
//
// Returns 202 immediately — generation runs async. The frontend polls
// GET /results every 3 s while on the ProcessingStep screen.
//
// The engine module is required lazily inside the handler so that a missing
// file never crashes the server at boot (returns 503 instead).
router.post(
  '/generate-recommendations',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    // Lazy require — safe even if the file is not yet deployed
    let engine;
    try {
      engine = require('../modules/student-onboarding/services/recommendation-engine');
    } catch (loadErr) {
      logger.error('[StudentOnboarding] recommendation-engine module not found', {
        userId,
        err: loadErr.message,
        hint: 'Deploy src/modules/student-onboarding/services/recommendation-engine.js',
      });
      throw new AppError(
        'Recommendation engine not available. Please deploy the Phase 1 service file.',
        503,
        { code: 'ENGINE_NOT_DEPLOYED' },
        ErrorCodes.INTERNAL_ERROR,
      );
    }

    logger.info('[StudentOnboarding] generate-recommendations requested', { userId });

    // Fire-and-forget — return 202 immediately so the frontend can start polling
    engine.generateRecommendations(userId).catch((err) => {
      logger.error('[StudentOnboarding] generate-recommendations failed', {
        userId,
        err: err.message,
      });
    });

    return res.status(202).json({
      success: true,
      data: { message: 'Recommendation generation started. Poll GET /results for completion.' },
    });
  }),
);

// GET /results
// Returns the completed RecommendationResult, or { result: null } while
// generation is still in progress.
// The frontend ProcessingStep polls this every 3 s until result is non-null.
router.get(
  '/results',
  asyncHandler(async (req, res) => {
    const userId = getUserId(req);

    const { data, error } = await supabase
      .from('student_recommendation_results')
      .select('result_json, generated_at, engine_version')
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      throw new AppError(error.message, 500, { code: error.code }, ErrorCodes.INTERNAL_ERROR);
    }

    if (!data) {
      return res.status(200).json({ success: true, data: { result: null } });
    }

    let parsed;
    try {
      parsed = typeof data.result_json === 'string'
        ? JSON.parse(data.result_json)
        : data.result_json;
    } catch {
      throw new AppError(
        'Failed to parse recommendation result',
        500,
        {},
        ErrorCodes.INTERNAL_ERROR,
      );
    }

    return res.status(200).json({
      success: true,
      data: {
        result: parsed,
        generatedAt: data.generated_at,
        engineVersion: data.engine_version,
      },
    });
  }),
);

module.exports = router;