-- ============================================================
-- PATCH 31 | FILE 2 OF 5
-- supabase/migrations/20260413_002_ai_tables.sql
-- AI Feature Tables — Delta-safe live schema remediation
-- Phase 0 aligned
-- ============================================================

-- ============================================================
-- ai_usage_logs — additive only
-- ============================================================
alter table public.ai_usage_logs
  add column if not exists feature         text,
  add column if not exists model           text,
  add column if not exists tokens_in       integer,
  add column if not exists tokens_out      integer,
  add column if not exists cost_usd        numeric(10,6),
  add column if not exists session_id      text,
  add column if not exists job_id          text,
  add column if not exists error_message   text;

comment on table public.ai_usage_logs is
  'Append-only ledger for all AI service calls. Replaces ghost table references.';

-- ============================================================
-- career_health_index — additive only
-- ============================================================
alter table public.career_health_index
  add column if not exists raw_signals         jsonb,
  add column if not exists gap_analysis        jsonb,
  add column if not exists strengths           jsonb,
  add column if not exists weaknesses          jsonb,
  add column if not exists market_alignment    numeric(5,2),
  add column if not exists growth_trajectory   text,
  add column if not exists is_latest           boolean not null default true;

comment on table public.career_health_index is
  'Point-in-time career health snapshots generated by chiV2.';

create unique index if not exists career_health_index_user_latest_uq
  on public.career_health_index (user_id)
  where is_latest = true;

create or replace function public.career_health_set_latest()
returns trigger
language plpgsql
as $$
begin
  update public.career_health_index
     set is_latest = false
   where user_id = new.user_id
     and id != new.id
     and is_latest = true;
  return new;
end;
$$;

drop trigger if exists trg_career_health_set_latest
on public.career_health_index;

create trigger trg_career_health_set_latest
  after insert on public.career_health_index
  for each row
  execute function public.career_health_set_latest();

-- ============================================================
-- career_predictions — fully missing table
-- IMPORTANT: user_id must be TEXT (Phase 0 canonical identity)
-- ============================================================
create table if not exists public.career_predictions (
  id                  uuid primary key default gen_random_uuid(),
  user_id             text not null references public.user_profiles(id) on delete cascade,
  prediction_type     text not null,
  horizon_months      integer,
  input_snapshot      jsonb,
  predictions         jsonb not null default '[]',
  confidence_score    numeric(5,2),
  model_version       text,
  engine              text,
  status              text not null default 'pending',
  completed_at        timestamptz,
  expires_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.career_predictions is
  'AI-generated career trajectory predictions.';

drop trigger if exists trg_career_predictions_updated_at
on public.career_predictions;

create trigger trg_career_predictions_updated_at
  before update on public.career_predictions
  for each row
  execute function public.set_updated_at();

-- ============================================================
-- career_simulations — drifted live table
-- ALTER ONLY (never recreate)
-- ============================================================
alter table public.career_simulations
  add column if not exists scenario            jsonb,
  add column if not exists outcomes            jsonb,
  add column if not exists skill_gaps          jsonb,
  add column if not exists recommended_actions jsonb,
  add column if not exists engine_version      text;

comment on table public.career_simulations is
  'What-if career simulation scenarios.';

drop trigger if exists trg_career_simulations_updated_at
on public.career_simulations;

create trigger trg_career_simulations_updated_at
  before update on public.career_simulations
  for each row
  execute function public.set_updated_at();